
server:
  #tomcat最大线程数，默认为200
  max-threads: 800
  # Tomcat启动初始化的线程数，默认值25
  min-spare-threads: 30
  #服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    #应用的访问路径
    context-path: /base-backend
  tomcat:
    #tomcat的URI编码
    uri-encoding: UTF-8

# Spring配置 
spring:
  messages:
    # 资源信息 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      # 文件上传单个文件大小
      max-file-size: 10MB
      # 文件上传设置总上传的文件大小
      max-request-size: 20MB
  datasource:
    ##spring数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置检测连接是否有效
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 1
      webStatFilter:
        enabled: true
      # 主库数据源
      master:
        password: 123456
        url: jdbc:postgresql://192.168.10.235:5432/basics_yngishere?setUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
        username: postgres
      # 从库数据源开关/默认关闭
      slave:
        enabled: false
        password: ''
        url: ''
        username: ''
      statViewServlet:
        # 设置白名单，不填则允许所有访问
        allow: ''
        url-pattern: /druid/*
        # 控制台管理用户名和密码
      # 慢SQL记录
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 1000
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.10.235
    # 密码
    password: 123456
    # 数据库索引
    database: 0
    # 端口，默认为6379
    port: 6379
    # 连接超时时间
    timeout: 10S
    # 连接池
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        m-idle: 0
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        
springdoc:
  api-docs:
    # 访问路径
    path: /doc
    enabled: ${config.swaggerEnabled}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${config.swaggerEnabled}
  info:
    version: 1.0.0
    title: Spring API
    desc: sample application
    license: Apache 2.0
    url: http://springdoc.org
        
# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: asdfaxcvr1395s35d
  # 令牌有效期（默认30分钟）
  expireTime: 30
  
ynfy:
  path:
    # 文件访问api
    accessPath: /api/**
    localPath: ${config.swaggerEnabled}
  thread:
    # 核心线程池大小
    corePoolSize: 10
    # 最大可创建的线程数
    maxPoolSize: 30
    # 队列最大长度
    queueCapacity: 100
    # 线程池维护线程所允许的空闲时间
    keepAliveSeconds: 60