server:
  #tomcat最大线程数，默认为200
  max-threads: 800
  # Tomcat启动初始化的线程数，默认值25
  min-spare-threads: 30
  #服务器的HTTP端口，默认为8080
  port: 8000
  servlet:
    #应用的访问路径
    context-path: /base-backend
  tomcat:
    #tomcat的URI编码
    uri-encoding: UTF-8

# Spring配置 
spring:
  messages:
    # 资源信息 国际化资源文件路径
    basename: i18n/messages
  servlet:
    multipart:
      # 文件上传单个文件大小
      max-file-size: 10MB
      # 文件上传设置总上传的文件大小
      max-request-size: 20MB
  datasource:
    ##spring数据源配置
    driverClassName: org.postgresql.Driver
    ## 单数据源 移除 druid 依赖, 并取消注释以下配置, 注释所有 druid 配置
    password: ${config.datasource.password}
    url: jdbc:postgresql://${config.datasource.url}:5432/icbc?setUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: ${config.datasource.username}
  # redis 配置
  redis:
    # 地址
    host: ${config.redis.host}
    # 密码
    password: ${config.redis.password}
    # 数据库索引
    database: ${config.redis.database}
    # 端口，默认为6379
    port: ${config.redis.port}
    # 连接超时时间
    timeout: 10S
    # 连接池
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        m-idle: 0
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 手动绕过 autoconfigure - RedisCacheConfiguration
#org:
#  springframework:
#    boot:
#      autoconfigure:
#        cache:
#          RedisCacheConfiguration:
#            AutoConfigureAfter: tech.ynfy.frame.config.redis.RedisConfig
#            

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:tech/ynfy/module/**/mapper/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
      #逻辑删除配置
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      logic-delete-value: 1
      logic-not-delete-value: 0

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

ynfy:
  path:
    # 文件访问api
    accessPath: /api/**
    localPath: ${config.swaggerEnabled}
  thread:
    # 核心线程池大小
    corePoolSize: 10
    # 最大可创建的线程数
    maxPoolSize: 30
    # 队列最大长度
    queueCapacity: 100
    # 线程池维护线程所允许的空闲时间
    keepAliveSeconds: 60


springdoc:
  api-docs:
    # 访问路径
    path: /doc
    enabled: ${config.swaggerEnabled}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${config.swaggerEnabled}
  info:
    version: 1.0.0 - SNAPSHOT
    title: Spring API
    desc: sample application
    license: Apache 2.0
    url: http://springdoc.org