config:
  # 是否开启 swagger
  swaggerEnabled: true
  # 本地文件路径
  localPath: /Users/vjf/Projects/idea/logs/base-end
  # redis 配置
  redis:
    # 地址
    host: remoteUrl
    # 密码
    password: 123456
    # 数据库索引
    database: 0
    # 端口，默认为6379
    port: 6379
  datasource:
    password: postgres
    url: remoteUrl
    username: postgres
    
mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl