config:
  # 是否开启 swagger
  swaggerEnabled: true
  # 本地文件路径
  localPath: /Users/vjf/Projects/idea/logs/base-end
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 密码
    password: 123456
    # 数据库索引
    database: 0
    # 端口，默认为6379
    port: 6379
  datasource:
    password: peak1203
    url: localhost
    username: postgres